### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\tmp\apiproxy-[a unix time]-[some random changing characters].zip'

### ISSUE THREAD

**Issue by iamjoshuabcxvii** [DinoChiesa/Edge-OAuthV2-PKCE-Proxy#1]
I'm running the command
node ./importAndDeploy.js -v -o MyORG -e test -d 

> node ./importAndDeploy.js -v -o MyORG -e test -d ..

But encountering this error....

> [2019-Jun-17 15:29:40] found stashed token.
> [2019-Jun-17 15:29:40] valid and not expired
> [2019-Jun-17 15:29:40] connected
> [2019-Jun-17 15:29:40] importing a proxy
> [2019-Jun-17 15:29:40] found name: oauth2-ac-pkce
> [2019-Jun-17 15:29:40] import apiproxy oauth2-ac-pkce from dir C:\Users\joshu\OneDrive\Desktop\Edge-OAuthV2-PKCE-Proxy-master
> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: ENOENT: no such file or directory, open 'C:\tmp\apiproxy-1560756580540-1j6l6tr9mkk.zip'
> Emitted 'error' event at:
>     at WriteStream.onerror (C:\Users\joshu\OneDrive\Desktop\Edge-OAuthV2-PKCE-Proxy-master\tools\node_modules\readable-stream\lib\_stream_readable.js:640:52)
>     at WriteStream.emit (events.js:198:13)
>     at lazyFs.open (internal/fs/streams.js:277:12)
>     at FSReqWrap.args [as oncomplete] (fs.js:140:20)

I already cleaned my cache and did an npm install, but its still the same,how do I fix this?. TIA.

**Comment by iamjoshuabcxvii** [comment]
PS:
I tried running this command in Ubuntu, I got a different error but it got fixed when I tried to run it with SUDO. How do I fix this on windows 10 though?..
